using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Daan.Interface.Entity
{

    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public class DAAN_LIS_REPORT : BaseDomain
    {


        #region Private Members
        private bool isChanged;
        private bool isDeleted;
        private string dAAN_ID;

       
        private string dAAN_BAR_CODE;
        private string dAAN_STATUS;
        private byte[] dAAN_JPG;
        #endregion

        public DAAN_LIS_REPORT()
        {
            dAAN_ID = null;
            dAAN_BAR_CODE = null;
            dAAN_JPG = new byte[0];
            dAAN_STATUS = null;
        }


        /// <summary>
        /// 主键ID
        /// </summary>	
        [LogInfo("主键ID")]
        public string DAAN_ID
        {
            get { return dAAN_ID; }
            set
            {
                if (value != null && value.Length > 20)
                    throw new ArgumentOutOfRangeException("Invalid value for dAAN_ID", value, value.ToString());

                isChanged |= (dAAN_ID != value); dAAN_ID = value;
            }
        }


        /// <summary>
        /// 医院条码
        /// </summary>	
        [LogInfo("医院条码")]
        public string DAAN_BAR_CODE
        {
            get { return dAAN_BAR_CODE; }
            set
            {
                if (value != null && value.Length > 20)
                    throw new ArgumentOutOfRangeException("Invalid value for dAAN_BAR_CODE", value, value.ToString());

                isChanged |= (dAAN_BAR_CODE != value); dAAN_BAR_CODE = value;
            }
        }


        /// <summary>
        /// 状态
        /// </summary>	
        [LogInfo("状态")]
        public string DAAN_STATUS
        {
            get { return dAAN_STATUS; }
            set
            {
                if (value != null && value.Length > 20)
                    throw new ArgumentOutOfRangeException("Invalid value for dAAN_STATUS", value, value.ToString());

                isChanged |= (dAAN_STATUS != value); dAAN_STATUS = value;
            }
        }

        /// <summary>
        /// 图片数据  BASE64编码
        /// </summary>	
        [LogInfo("图片数据  BASE64编码")]
        public byte[] DAAN_JPG
        {
            get { return dAAN_JPG; }
            set { isChanged |= (dAAN_JPG != value); dAAN_JPG = value; }
        }

    }
}
